const hobbies = [
  "Reading",
  "Traveling",
  "Cooking",
  "Gardening",
  "Painting",
  "Photography",
  "Writing",
  "Yoga",
  "Fitness",
  "Music",
  "Dance",
  "Hiking",
  "Cycling",
  "Swimming",
  "Fishing",
  "Travel Photography",
  "DIY Projects",
  "Cooking/Baking",
  "Crafting",
  "Meditation",
  "Bird Watching",
  "Running",
  "Knitting",
  "Embroidery",
  "Video Gaming",
  "Playing an Instrument",
  "Blogging",
  "Sewing",
  "Chess",
  "Theater",
  "Pottery",
  "Volunteering",
  "Journal Writing",
  "Rock Climbing",
  "Stand-Up Comedy",
  "Watching Movies",
  "Gardening/Vegetable Growing",
  "Biking",
  "Calligraphy",
  "Ice Skating",
  "Horseback Riding",
  "Journaling",
  "Fishing",
  "Outdoor Camping",
  "Listening to Music",
  "Art Drawing",
  "Nature Walks",
  "Meditative Art",
  "Astronomy",
  "Fencing",
  "Birdwatching",
  "Model Making",
  "DIY Home Improvement",
  "Calligraphy",
  "Creative Writing",
  "Video Editing",
  "DIY Furniture",
  "Meditation",
  "Podcasts Listening",
  "Baking",
  "Pottery",
  "Interior Design",
  "Tabletop Games",
  "Fishing",
  "Scuba Diving",
  "Traveling",
  "Surfing",
  "Drawing Comics",
  "Graphic Design",
  "Learning a Language",
  "Gardening",
  "Origami",
  "Quilting",
  "Home Decor",
  "Video Creation",
  "Knitting",
  "Crafts",
  "Performing Arts",
  "Woodworking",
  "Sculpture",
  "Quilting",
  "Photography",
  "Graphic Design",
  "Art Restoration",
  "Metalworking",
  "Soap Making",
  "Bird Watching",
  "Antique Collecting",
  "Textile Art",
  "Dancing",
  "DJing",
  "Calligraphy",
  "Origami",
  "Podcast Production",
];
