export const locations = {
  Tallinn: "Tallinn",
  Tartu: "Tartu",
  Narva: "Narva",
  Pärnu: "Pärnu",
  KohtlaJärve: "Kohtla-Järve",
  Viljandi: "Viljandi",
  Rakvere: "Rakvere",
  Maardu: "Maardu",
  Sillamäe: "Sillamäe",
  Kuressaare: "Kuressaare",
  Võru: "Võru",
  Valga: "Valga",
  Haapsalu: "Haapsalu",
  Jõhvi: "Jõhvi",
  Paide: "Paide",
  Keila: "Keila",
  Türi: "Türi",
  Kiviõli: "Kiviõli",
  Elva: "Elva",
  Saue: "Saue",
};
